services:
  mysql:
    image: 'mysql:8'
    environment:
      - 'MYSQL_DATABASE=ufo-sightings'
      - 'MYSQL_PASSWORD=the-truth-is-out-there'
      - 'MYSQL_ROOT_PASSWORD=the-root-is-out-there'
      - 'MYSQL_USER=dearbhla'
    ports:
      - '3306:3306'
    volumes:
      - ./docker/ufo-sightings-volume:/var/lib/mysql
