package org.ufo.sightings.controllers;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.ufo.sightings.entities.Sightings;
import org.ufo.sightings.repositories.SightingRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URLs start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called sightingRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private SightingRepository sightingRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewSighting (@RequestParam LocalDateTime datetime
            , @RequestParam String comments) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        Sightings s = new Sightings();
        s.setDatetime(datetime);
        s.setComments(comments);
        sightingRepository.save(s);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Sightings> getAllSightings() {
        // This returns a JSON or XML with the sightings
        return sightingRepository.findAll();
    }
}
